### ISSUE TITLE
PIN BLOCK FORMAT

### ISSUE THREAD

**Issue by scalpovich** [hosseinmd/data-crypto#1]
Hi,
Great package
Is it possible to use differnet format of bin block
The current version seems to encrypt on format 0.
According to ISO 9564 there is many other format.

Kindly assit for format 1

**Comment by fardad-dev** [comment]
Ok, I will check it today

**Comment by fardad-dev** [comment]
I have added Format 1 function, please check it

**Comment by scalpovich** [comment]
ok thank you
