### ISSUE TITLE
Wrong PINBLOCK ISO-0 calculation

### ISSUE THREAD

**Issue by rfitoc** [hosseinmd/data-crypto#3]
Hi,

In pinBlockFormat0() function :
 
>  const preparedPAN = PAN.slice(3, 15).padStart(16, "0");

should be:
  
> const preparedPAN = PAN.slice(-12).padStart(16, "0");

The "prepared PAN" it must be the last 12 digits of the PAN with zero padding until 16 characters. In this mode we take into account PANs of different length.

 ** IMPORTANT: PAN must not have LRC

**Comment by fardad-dev** [comment]
Please give me a PR

**Comment by fardad-dev** [comment]
Could you give me a different of current result and correct result?
