### ISSUE TITLE
Triple DES output size 

### ISSUE THREAD

**Issue by kerbay** [hosseinmd/data-crypto#4]
Hi, 
I have a 28 bytes long text hex value and 16 bytes of key hex value. When I decrypted Triple DES I always get 8 bytes encripted hex value. I want to get whole decrypted data. 

Also, what is the mode of the 3DES? Is it CBC , ECB or anything else?

Thanks in advance !

**Comment by kerbay** [comment]
my hex value: 
`const hexNum = 'FB9235F4E4037F2327DCC8964F1F9B8C30F42C8E2FFF224A99029000';
`
and key: 
`const keyENC = '979EC13B1CBFE9DCD01AB0FED307EAE5';
`

and output should be `04303130365F36063034303030305C026175` 

but I only get first 8 bytes of this.

**Comment by fardad-dev** [comment]
Give me time to test it. I will tell you the result.

**Comment by kerbay** [comment]
> Give me time to test it. I will tell you the result.

Hi @hosseinmd ,
Any progress?

**Comment by fardad-dev** [comment]
Fixed V1.4.4.
